<?php

namespace jamesiarmes\PEWS\API\Message;

use jamesiarmes\PEWS\API\Message;

/**
 * Class representing ResponseCodeType
 *
 * Represents the message keys that can be returned by response error messages
 * XSD Type: ResponseCodeType
 */
class ResponseCodeType extends Message
{

    const NOERROR = 'NOERROR';

    const ERRORACCESSDENIED = 'ERRORACCESSDENIED';

    const ERRORACCESSMODESPECIFIED = 'ERRORACCESSMODESPECIFIED';

    const ERRORACCOUNTDISABLED = 'ERRORACCOUNTDISABLED';

    const ERRORADDDELEGATESFAILED = 'ERRORADDDELEGATESFAILED';

    const ERRORADDRESSSPACENOTFOUND = 'ERRORADDRESSSPACENOTFOUND';

    const ERRORADOPERATION = 'ERRORADOPERATION';

    const ERRORADSESSIONFILTER = 'ERRORADSESSIONFILTER';

    const ERRORADUNAVAILABLE = 'ERRORADUNAVAILABLE';

    const ERRORAUTODISCOVERFAILED = 'ERRORAUTODISCOVERFAILED';

    const ERRORAFFECTEDTASKOCCURRENCESREQUIRED = 'ERRORAFFECTEDTASKOCCURRENCESREQUIRED';

    const ERRORATTACHMENTNESTLEVELLIMITEXCEEDED = 'ERRORATTACHMENTNESTLEVELLIMITEXCEEDED';

    const ERRORATTACHMENTSIZELIMITEXCEEDED = 'ERRORATTACHMENTSIZELIMITEXCEEDED';

    const ERRORAVAILABILITYCONFIGNOTFOUND = 'ERRORAVAILABILITYCONFIGNOTFOUND';

    const ERRORBATCHPROCESSINGSTOPPED = 'ERRORBATCHPROCESSINGSTOPPED';

    const ERRORCALENDARCANNOTMOVEORCOPYOCCURRENCE = 'ERRORCALENDARCANNOTMOVEORCOPYOCCURRENCE';

    const ERRORCALENDARCANNOTUPDATEDELETEDITEM = 'ERRORCALENDARCANNOTUPDATEDELETEDITEM';

    const ERRORCALENDARCANNOTUSEIDFOROCCURRENCEID = 'ERRORCALENDARCANNOTUSEIDFOROCCURRENCEID';

    const ERRORCALENDARCANNOTUSEIDFORRECURRINGMASTERID = 'ERRORCALENDARCANNOTUSEIDFORRECURRINGMASTERID';

    const ERRORCALENDARDURATIONISTOOLONG = 'ERRORCALENDARDURATIONISTOOLONG';

    const ERRORCALENDARENDDATEISEARLIERTHANSTARTDATE = 'ERRORCALENDARENDDATEISEARLIERTHANSTARTDATE';

    const ERRORCALENDARFOLDERISINVALIDFORCALENDARVIEW = 'ERRORCALENDARFOLDERISINVALIDFORCALENDARVIEW';

    const ERRORCALENDARINVALIDATTRIBUTEVALUE = 'ERRORCALENDARINVALIDATTRIBUTEVALUE';

    const ERRORCALENDARINVALIDDAYFORTIMECHANGEPATTERN = 'ERRORCALENDARINVALIDDAYFORTIMECHANGEPATTERN';

    const ERRORCALENDARINVALIDDAYFORWEEKLYRECURRENCE = 'ERRORCALENDARINVALIDDAYFORWEEKLYRECURRENCE';

    const ERRORCALENDARINVALIDPROPERTYSTATE = 'ERRORCALENDARINVALIDPROPERTYSTATE';

    const ERRORCALENDARINVALIDPROPERTYVALUE = 'ERRORCALENDARINVALIDPROPERTYVALUE';

    const ERRORCALENDARINVALIDRECURRENCE = 'ERRORCALENDARINVALIDRECURRENCE';

    const ERRORCALENDARINVALIDTIMEZONE = 'ERRORCALENDARINVALIDTIMEZONE';

    const ERRORCALENDARISCANCELLEDFORACCEPT = 'ERRORCALENDARISCANCELLEDFORACCEPT';

    const ERRORCALENDARISCANCELLEDFORDECLINE = 'ERRORCALENDARISCANCELLEDFORDECLINE';

    const ERRORCALENDARISCANCELLEDFORREMOVE = 'ERRORCALENDARISCANCELLEDFORREMOVE';

    const ERRORCALENDARISCANCELLEDFORTENTATIVE = 'ERRORCALENDARISCANCELLEDFORTENTATIVE';

    const ERRORCALENDARISDELEGATEDFORACCEPT = 'ERRORCALENDARISDELEGATEDFORACCEPT';

    const ERRORCALENDARISDELEGATEDFORDECLINE = 'ERRORCALENDARISDELEGATEDFORDECLINE';

    const ERRORCALENDARISDELEGATEDFORREMOVE = 'ERRORCALENDARISDELEGATEDFORREMOVE';

    const ERRORCALENDARISDELEGATEDFORTENTATIVE = 'ERRORCALENDARISDELEGATEDFORTENTATIVE';

    const ERRORCALENDARISNOTORGANIZER = 'ERRORCALENDARISNOTORGANIZER';

    const ERRORCALENDARISORGANIZERFORACCEPT = 'ERRORCALENDARISORGANIZERFORACCEPT';

    const ERRORCALENDARISORGANIZERFORDECLINE = 'ERRORCALENDARISORGANIZERFORDECLINE';

    const ERRORCALENDARISORGANIZERFORREMOVE = 'ERRORCALENDARISORGANIZERFORREMOVE';

    const ERRORCALENDARISORGANIZERFORTENTATIVE = 'ERRORCALENDARISORGANIZERFORTENTATIVE';

    const ERRORCALENDAROCCURRENCEINDEXISOUTOFRECURRENCERANGE = 'ERRORCALENDAROCCURRENCEINDEXISOUTOFRECURRENCERANGE';

    const ERRORCALENDAROCCURRENCEISDELETEDFROMRECURRENCE = 'ERRORCALENDAROCCURRENCEISDELETEDFROMRECURRENCE';

    const ERRORCALENDAROUTOFRANGE = 'ERRORCALENDAROUTOFRANGE';

    const ERRORCALENDARMEETINGREQUESTISOUTOFDATE = 'ERRORCALENDARMEETINGREQUESTISOUTOFDATE';

    const ERRORCALENDARVIEWRANGETOOBIG = 'ERRORCALENDARVIEWRANGETOOBIG';

    const ERRORCALLERISINVALIDADACCOUNT = 'ERRORCALLERISINVALIDADACCOUNT';

    const ERRORCANNOTCREATECALENDARITEMINNONCALENDARFOLDER = 'ERRORCANNOTCREATECALENDARITEMINNONCALENDARFOLDER';

    const ERRORCANNOTCREATECONTACTINNONCONTACTFOLDER = 'ERRORCANNOTCREATECONTACTINNONCONTACTFOLDER';

    const ERRORCANNOTCREATEPOSTITEMINNONMAILFOLDER = 'ERRORCANNOTCREATEPOSTITEMINNONMAILFOLDER';

    const ERRORCANNOTCREATETASKINNONTASKFOLDER = 'ERRORCANNOTCREATETASKINNONTASKFOLDER';

    const ERRORCANNOTDELETEOBJECT = 'ERRORCANNOTDELETEOBJECT';

    const ERRORCANNOTOPENFILEATTACHMENT = 'ERRORCANNOTOPENFILEATTACHMENT';

    const ERRORCANNOTDELETETASKOCCURRENCE = 'ERRORCANNOTDELETETASKOCCURRENCE';

    const ERRORCANNOTEMPTYFOLDER = 'ERRORCANNOTEMPTYFOLDER';

    const ERRORCANNOTSETCALENDARPERMISSIONONNONCALENDARFOLDER = 'ERRORCANNOTSETCALENDARPERMISSIONONNONCALENDARFOLDER';

    const ERRORCANNOTSETNONCALENDARPERMISSIONONCALENDARFOLDER = 'ERRORCANNOTSETNONCALENDARPERMISSIONONCALENDARFOLDER';

    const ERRORCANNOTSETPERMISSIONUNKNOWNENTRIES = 'ERRORCANNOTSETPERMISSIONUNKNOWNENTRIES';

    const ERRORCANNOTUSEFOLDERIDFORITEMID = 'ERRORCANNOTUSEFOLDERIDFORITEMID';

    const ERRORCANNOTUSEITEMIDFORFOLDERID = 'ERRORCANNOTUSEITEMIDFORFOLDERID';

    const ERRORCHANGEKEYREQUIRED = 'ERRORCHANGEKEYREQUIRED';

    const ERRORCHANGEKEYREQUIREDFORWRITEOPERATIONS = 'ERRORCHANGEKEYREQUIREDFORWRITEOPERATIONS';

    const ERRORCLIENTDISCONNECTED = 'ERRORCLIENTDISCONNECTED';

    const ERRORCONNECTIONFAILED = 'ERRORCONNECTIONFAILED';

    const ERRORCONTAINSFILTERWRONGTYPE = 'ERRORCONTAINSFILTERWRONGTYPE';

    const ERRORCONTENTCONVERSIONFAILED = 'ERRORCONTENTCONVERSIONFAILED';

    const ERRORCORRUPTDATA = 'ERRORCORRUPTDATA';

    const ERRORCREATEITEMACCESSDENIED = 'ERRORCREATEITEMACCESSDENIED';

    const ERRORCREATEMANAGEDFOLDERPARTIALCOMPLETION = 'ERRORCREATEMANAGEDFOLDERPARTIALCOMPLETION';

    const ERRORCREATESUBFOLDERACCESSDENIED = 'ERRORCREATESUBFOLDERACCESSDENIED';

    const ERRORCROSSMAILBOXMOVECOPY = 'ERRORCROSSMAILBOXMOVECOPY';

    const ERRORCROSSSITEREQUEST = 'ERRORCROSSSITEREQUEST';

    const ERRORDATASIZELIMITEXCEEDED = 'ERRORDATASIZELIMITEXCEEDED';

    const ERRORDATASOURCEOPERATION = 'ERRORDATASOURCEOPERATION';

    const ERRORDELEGATEALREADYEXISTS = 'ERRORDELEGATEALREADYEXISTS';

    const ERRORDELEGATECANNOTADDOWNER = 'ERRORDELEGATECANNOTADDOWNER';

    const ERRORDELEGATEMISSINGCONFIGURATION = 'ERRORDELEGATEMISSINGCONFIGURATION';

    const ERRORDELEGATENOUSER = 'ERRORDELEGATENOUSER';

    const ERRORDELEGATEVALIDATIONFAILED = 'ERRORDELEGATEVALIDATIONFAILED';

    const ERRORDELETEDISTINGUISHEDFOLDER = 'ERRORDELETEDISTINGUISHEDFOLDER';

    const ERRORDELETEITEMSFAILED = 'ERRORDELETEITEMSFAILED';

    const ERRORDISTINGUISHEDUSERNOTSUPPORTED = 'ERRORDISTINGUISHEDUSERNOTSUPPORTED';

    const ERRORDISTRIBUTIONLISTMEMBERNOTEXIST = 'ERRORDISTRIBUTIONLISTMEMBERNOTEXIST';

    const ERRORDUPLICATEINPUTFOLDERNAMES = 'ERRORDUPLICATEINPUTFOLDERNAMES';

    const ERRORDUPLICATEUSERIDSSPECIFIED = 'ERRORDUPLICATEUSERIDSSPECIFIED';

    const ERROREMAILADDRESSMISMATCH = 'ERROREMAILADDRESSMISMATCH';

    const ERROREVENTNOTFOUND = 'ERROREVENTNOTFOUND';

    const ERROREXCEEDEDCONNECTIONCOUNT = 'ERROREXCEEDEDCONNECTIONCOUNT';

    const ERROREXCEEDEDSUBSCRIPTIONCOUNT = 'ERROREXCEEDEDSUBSCRIPTIONCOUNT';

    const ERROREXCEEDEDFINDCOUNTLIMIT = 'ERROREXCEEDEDFINDCOUNTLIMIT';

    const ERROREXPIREDSUBSCRIPTION = 'ERROREXPIREDSUBSCRIPTION';

    const ERRORFOLDERCORRUPT = 'ERRORFOLDERCORRUPT';

    const ERRORFOLDERNOTFOUND = 'ERRORFOLDERNOTFOUND';

    const ERRORFOLDERPROPERTREQUESTFAILED = 'ERRORFOLDERPROPERTREQUESTFAILED';

    const ERRORFOLDERSAVE = 'ERRORFOLDERSAVE';

    const ERRORFOLDERSAVEFAILED = 'ERRORFOLDERSAVEFAILED';

    const ERRORFOLDERSAVEPROPERTYERROR = 'ERRORFOLDERSAVEPROPERTYERROR';

    const ERRORFOLDEREXISTS = 'ERRORFOLDEREXISTS';

    const ERRORFREEBUSYGENERATIONFAILED = 'ERRORFREEBUSYGENERATIONFAILED';

    const ERRORGETSERVERSECURITYDESCRIPTORFAILED = 'ERRORGETSERVERSECURITYDESCRIPTORFAILED';

    const ERRORIMPERSONATEUSERDENIED = 'ERRORIMPERSONATEUSERDENIED';

    const ERRORIMPERSONATIONDENIED = 'ERRORIMPERSONATIONDENIED';

    const ERRORIMPERSONATIONFAILED = 'ERRORIMPERSONATIONFAILED';

    const ERRORINCORRECTSCHEMAVERSION = 'ERRORINCORRECTSCHEMAVERSION';

    const ERRORINCORRECTUPDATEPROPERTYCOUNT = 'ERRORINCORRECTUPDATEPROPERTYCOUNT';

    const ERRORINDIVIDUALMAILBOXLIMITREACHED = 'ERRORINDIVIDUALMAILBOXLIMITREACHED';

    const ERRORINSUFFICIENTRESOURCES = 'ERRORINSUFFICIENTRESOURCES';

    const ERRORINTERNALSERVERERROR = 'ERRORINTERNALSERVERERROR';

    const ERRORINTERNALSERVERTRANSIENTERROR = 'ERRORINTERNALSERVERTRANSIENTERROR';

    const ERRORINVALIDACCESSLEVEL = 'ERRORINVALIDACCESSLEVEL';

    const ERRORINVALIDARGUMENT = 'ERRORINVALIDARGUMENT';

    const ERRORINVALIDATTACHMENTID = 'ERRORINVALIDATTACHMENTID';

    const ERRORINVALIDATTACHMENTSUBFILTER = 'ERRORINVALIDATTACHMENTSUBFILTER';

    const ERRORINVALIDATTACHMENTSUBFILTERTEXTFILTER = 'ERRORINVALIDATTACHMENTSUBFILTERTEXTFILTER';

    const ERRORINVALIDAUTHORIZATIONCONTEXT = 'ERRORINVALIDAUTHORIZATIONCONTEXT';

    const ERRORINVALIDCHANGEKEY = 'ERRORINVALIDCHANGEKEY';

    const ERRORINVALIDCLIENTSECURITYCONTEXT = 'ERRORINVALIDCLIENTSECURITYCONTEXT';

    const ERRORINVALIDCOMPLETEDATE = 'ERRORINVALIDCOMPLETEDATE';

    const ERRORINVALIDCONTACTEMAILADDRESS = 'ERRORINVALIDCONTACTEMAILADDRESS';

    const ERRORINVALIDCONTACTEMAILINDEX = 'ERRORINVALIDCONTACTEMAILINDEX';

    const ERRORINVALIDCROSSFORESTCREDENTIALS = 'ERRORINVALIDCROSSFORESTCREDENTIALS';

    const ERRORINVALIDDELEGATEPERMISSION = 'ERRORINVALIDDELEGATEPERMISSION';

    const ERRORINVALIDDELEGATEUSERID = 'ERRORINVALIDDELEGATEUSERID';

    const ERRORINVALIDEXCLUDESRESTRICTION = 'ERRORINVALIDEXCLUDESRESTRICTION';

    const ERRORINVALIDEXPRESSIONTYPEFORSUBFILTER = 'ERRORINVALIDEXPRESSIONTYPEFORSUBFILTER';

    const ERRORINVALIDEXTENDEDPROPERTY = 'ERRORINVALIDEXTENDEDPROPERTY';

    const ERRORINVALIDEXTENDEDPROPERTYVALUE = 'ERRORINVALIDEXTENDEDPROPERTYVALUE';

    const ERRORINVALIDFOLDERID = 'ERRORINVALIDFOLDERID';

    const ERRORINVALIDFOLDERTYPEFOROPERATION = 'ERRORINVALIDFOLDERTYPEFOROPERATION';

    const ERRORINVALIDFRACTIONALPAGINGPARAMETERS = 'ERRORINVALIDFRACTIONALPAGINGPARAMETERS';

    const ERRORINVALIDFREEBUSYVIEWTYPE = 'ERRORINVALIDFREEBUSYVIEWTYPE';

    const ERRORINVALIDID = 'ERRORINVALIDID';

    const ERRORINVALIDIDEMPTY = 'ERRORINVALIDIDEMPTY';

    const ERRORINVALIDIDMALFORMED = 'ERRORINVALIDIDMALFORMED';

    const ERRORINVALIDIDMALFORMEDEWSLEGACYIDFORMAT = 'ERRORINVALIDIDMALFORMEDEWSLEGACYIDFORMAT';

    const ERRORINVALIDIDMONIKERTOOLONG = 'ERRORINVALIDIDMONIKERTOOLONG';

    const ERRORINVALIDIDNOTANITEMATTACHMENTID = 'ERRORINVALIDIDNOTANITEMATTACHMENTID';

    const ERRORINVALIDIDRETURNEDBYRESOLVENAMES = 'ERRORINVALIDIDRETURNEDBYRESOLVENAMES';

    const ERRORINVALIDIDSTOREOBJECTIDTOOLONG = 'ERRORINVALIDIDSTOREOBJECTIDTOOLONG';

    const ERRORINVALIDIDTOOMANYATTACHMENTLEVELS = 'ERRORINVALIDIDTOOMANYATTACHMENTLEVELS';

    const ERRORINVALIDIDXML = 'ERRORINVALIDIDXML';

    const ERRORINVALIDINDEXEDPAGINGPARAMETERS = 'ERRORINVALIDINDEXEDPAGINGPARAMETERS';

    const ERRORINVALIDINTERNETHEADERCHILDNODES = 'ERRORINVALIDINTERNETHEADERCHILDNODES';

    const ERRORINVALIDITEMFOROPERATIONCREATEITEMATTACHMENT = 'ERRORINVALIDITEMFOROPERATIONCREATEITEMATTACHMENT';

    const ERRORINVALIDITEMFOROPERATIONCREATEITEM = 'ERRORINVALIDITEMFOROPERATIONCREATEITEM';

    const ERRORINVALIDITEMFOROPERATIONACCEPTITEM = 'ERRORINVALIDITEMFOROPERATIONACCEPTITEM';

    const ERRORINVALIDITEMFOROPERATIONDECLINEITEM = 'ERRORINVALIDITEMFOROPERATIONDECLINEITEM';

    const ERRORINVALIDITEMFOROPERATIONCANCELITEM = 'ERRORINVALIDITEMFOROPERATIONCANCELITEM';

    const ERRORINVALIDITEMFOROPERATIONEXPANDDL = 'ERRORINVALIDITEMFOROPERATIONEXPANDDL';

    const ERRORINVALIDITEMFOROPERATIONREMOVEITEM = 'ERRORINVALIDITEMFOROPERATIONREMOVEITEM';

    const ERRORINVALIDITEMFOROPERATIONSENDITEM = 'ERRORINVALIDITEMFOROPERATIONSENDITEM';

    const ERRORINVALIDITEMFOROPERATIONTENTATIVE = 'ERRORINVALIDITEMFOROPERATIONTENTATIVE';

    const ERRORINVALIDLOGONTYPE = 'ERRORINVALIDLOGONTYPE';

    const ERRORINVALIDMAILBOX = 'ERRORINVALIDMAILBOX';

    const ERRORINVALIDMANAGEDFOLDERPROPERTY = 'ERRORINVALIDMANAGEDFOLDERPROPERTY';

    const ERRORINVALIDMANAGEDFOLDERQUOTA = 'ERRORINVALIDMANAGEDFOLDERQUOTA';

    const ERRORINVALIDMANAGEDFOLDERSIZE = 'ERRORINVALIDMANAGEDFOLDERSIZE';

    const ERRORINVALIDMERGEDFREEBUSYINTERVAL = 'ERRORINVALIDMERGEDFREEBUSYINTERVAL';

    const ERRORINVALIDNAMEFORNAMERESOLUTION = 'ERRORINVALIDNAMEFORNAMERESOLUTION';

    const ERRORINVALIDOPERATION = 'ERRORINVALIDOPERATION';

    const ERRORINVALIDNETWORKSERVICECONTEXT = 'ERRORINVALIDNETWORKSERVICECONTEXT';

    const ERRORINVALIDOOFPARAMETER = 'ERRORINVALIDOOFPARAMETER';

    const ERRORINVALIDPAGINGMAXROWS = 'ERRORINVALIDPAGINGMAXROWS';

    const ERRORINVALIDPARENTFOLDER = 'ERRORINVALIDPARENTFOLDER';

    const ERRORINVALIDPERCENTCOMPLETEVALUE = 'ERRORINVALIDPERCENTCOMPLETEVALUE';

    const ERRORINVALIDPERMISSIONSETTINGS = 'ERRORINVALIDPERMISSIONSETTINGS';

    const ERRORINVALIDPHONECALLID = 'ERRORINVALIDPHONECALLID';

    const ERRORINVALIDPHONENUMBER = 'ERRORINVALIDPHONENUMBER';

    const ERRORINVALIDUSERINFO = 'ERRORINVALIDUSERINFO';

    const ERRORINVALIDPROPERTYAPPEND = 'ERRORINVALIDPROPERTYAPPEND';

    const ERRORINVALIDPROPERTYDELETE = 'ERRORINVALIDPROPERTYDELETE';

    const ERRORINVALIDPROPERTYFOREXISTS = 'ERRORINVALIDPROPERTYFOREXISTS';

    const ERRORINVALIDPROPERTYFOROPERATION = 'ERRORINVALIDPROPERTYFOROPERATION';

    const ERRORINVALIDPROPERTYREQUEST = 'ERRORINVALIDPROPERTYREQUEST';

    const ERRORINVALIDPROPERTYSET = 'ERRORINVALIDPROPERTYSET';

    const ERRORINVALIDPROPERTYUPDATESENTMESSAGE = 'ERRORINVALIDPROPERTYUPDATESENTMESSAGE';

    const ERRORINVALIDPROXYSECURITYCONTEXT = 'ERRORINVALIDPROXYSECURITYCONTEXT';

    const ERRORINVALIDPULLSUBSCRIPTIONID = 'ERRORINVALIDPULLSUBSCRIPTIONID';

    const ERRORINVALIDPUSHSUBSCRIPTIONURL = 'ERRORINVALIDPUSHSUBSCRIPTIONURL';

    const ERRORINVALIDRECIPIENTS = 'ERRORINVALIDRECIPIENTS';

    const ERRORINVALIDRECIPIENTSUBFILTER = 'ERRORINVALIDRECIPIENTSUBFILTER';

    const ERRORINVALIDRECIPIENTSUBFILTERCOMPARISON = 'ERRORINVALIDRECIPIENTSUBFILTERCOMPARISON';

    const ERRORINVALIDRECIPIENTSUBFILTERORDER = 'ERRORINVALIDRECIPIENTSUBFILTERORDER';

    const ERRORINVALIDRECIPIENTSUBFILTERTEXTFILTER = 'ERRORINVALIDRECIPIENTSUBFILTERTEXTFILTER';

    const ERRORINVALIDREFERENCEITEM = 'ERRORINVALIDREFERENCEITEM';

    const ERRORINVALIDREQUEST = 'ERRORINVALIDREQUEST';

    const ERRORINVALIDRESTRICTION = 'ERRORINVALIDRESTRICTION';

    const ERRORINVALIDROUTINGTYPE = 'ERRORINVALIDROUTINGTYPE';

    const ERRORINVALIDSCHEDULEDOOFDURATION = 'ERRORINVALIDSCHEDULEDOOFDURATION';

    const ERRORINVALIDSCHEMAVERSIONFORMAILBOXVERSION = 'ERRORINVALIDSCHEMAVERSIONFORMAILBOXVERSION';

    const ERRORINVALIDSECURITYDESCRIPTOR = 'ERRORINVALIDSECURITYDESCRIPTOR';

    const ERRORINVALIDSENDITEMSAVESETTINGS = 'ERRORINVALIDSENDITEMSAVESETTINGS';

    const ERRORINVALIDSERIALIZEDACCESSTOKEN = 'ERRORINVALIDSERIALIZEDACCESSTOKEN';

    const ERRORINVALIDSERVERVERSION = 'ERRORINVALIDSERVERVERSION';

    const ERRORINVALIDSID = 'ERRORINVALIDSID';

    const ERRORINVALIDSIPURI = 'ERRORINVALIDSIPURI';

    const ERRORINVALIDSMTPADDRESS = 'ERRORINVALIDSMTPADDRESS';

    const ERRORINVALIDSUBFILTERTYPE = 'ERRORINVALIDSUBFILTERTYPE';

    const ERRORINVALIDSUBFILTERTYPENOTATTENDEETYPE = 'ERRORINVALIDSUBFILTERTYPENOTATTENDEETYPE';

    const ERRORINVALIDSUBFILTERTYPENOTRECIPIENTTYPE = 'ERRORINVALIDSUBFILTERTYPENOTRECIPIENTTYPE';

    const ERRORINVALIDSUBSCRIPTION = 'ERRORINVALIDSUBSCRIPTION';

    const ERRORINVALIDSUBSCRIPTIONREQUEST = 'ERRORINVALIDSUBSCRIPTIONREQUEST';

    const ERRORINVALIDSYNCSTATEDATA = 'ERRORINVALIDSYNCSTATEDATA';

    const ERRORINVALIDTIMEINTERVAL = 'ERRORINVALIDTIMEINTERVAL';

    const ERRORINVALIDUSEROOFSETTINGS = 'ERRORINVALIDUSEROOFSETTINGS';

    const ERRORINVALIDUSERPRINCIPALNAME = 'ERRORINVALIDUSERPRINCIPALNAME';

    const ERRORINVALIDUSERSID = 'ERRORINVALIDUSERSID';

    const ERRORINVALIDUSERSIDMISSINGUPN = 'ERRORINVALIDUSERSIDMISSINGUPN';

    const ERRORINVALIDVALUEFORPROPERTY = 'ERRORINVALIDVALUEFORPROPERTY';

    const ERRORINVALIDWATERMARK = 'ERRORINVALIDWATERMARK';

    const ERRORIPGATEWAYNOTFOUND = 'ERRORIPGATEWAYNOTFOUND';

    const ERRORIRRESOLVABLECONFLICT = 'ERRORIRRESOLVABLECONFLICT';

    const ERRORITEMCORRUPT = 'ERRORITEMCORRUPT';

    const ERRORITEMNOTFOUND = 'ERRORITEMNOTFOUND';

    const ERRORITEMPROPERTYREQUESTFAILED = 'ERRORITEMPROPERTYREQUESTFAILED';

    const ERRORITEMSAVE = 'ERRORITEMSAVE';

    const ERRORITEMSAVEPROPERTYERROR = 'ERRORITEMSAVEPROPERTYERROR';

    const ERRORLEGACYMAILBOXFREEBUSYVIEWTYPENOTMERGED = 'ERRORLEGACYMAILBOXFREEBUSYVIEWTYPENOTMERGED';

    const ERRORLOCALSERVEROBJECTNOTFOUND = 'ERRORLOCALSERVEROBJECTNOTFOUND';

    const ERRORLOGONASNETWORKSERVICEFAILED = 'ERRORLOGONASNETWORKSERVICEFAILED';

    const ERRORMAILBOXCONFIGURATION = 'ERRORMAILBOXCONFIGURATION';

    const ERRORMAILBOXDATAARRAYEMPTY = 'ERRORMAILBOXDATAARRAYEMPTY';

    const ERRORMAILBOXDATAARRAYTOOBIG = 'ERRORMAILBOXDATAARRAYTOOBIG';

    const ERRORMAILBOXLOGONFAILED = 'ERRORMAILBOXLOGONFAILED';

    const ERRORMAILBOXMOVEINPROGRESS = 'ERRORMAILBOXMOVEINPROGRESS';

    const ERRORMAILBOXSTOREUNAVAILABLE = 'ERRORMAILBOXSTOREUNAVAILABLE';

    const ERRORMAILRECIPIENTNOTFOUND = 'ERRORMAILRECIPIENTNOTFOUND';

    const ERRORMAILTIPSDISABLED = 'ERRORMAILTIPSDISABLED';

    const ERRORMANAGEDFOLDERALREADYEXISTS = 'ERRORMANAGEDFOLDERALREADYEXISTS';

    const ERRORMANAGEDFOLDERNOTFOUND = 'ERRORMANAGEDFOLDERNOTFOUND';

    const ERRORMANAGEDFOLDERSROOTFAILURE = 'ERRORMANAGEDFOLDERSROOTFAILURE';

    const ERRORMEETINGSUGGESTIONGENERATIONFAILED = 'ERRORMEETINGSUGGESTIONGENERATIONFAILED';

    const ERRORMESSAGEDISPOSITIONREQUIRED = 'ERRORMESSAGEDISPOSITIONREQUIRED';

    const ERRORMESSAGESIZEEXCEEDED = 'ERRORMESSAGESIZEEXCEEDED';

    const ERRORMIMECONTENTCONVERSIONFAILED = 'ERRORMIMECONTENTCONVERSIONFAILED';

    const ERRORMIMECONTENTINVALID = 'ERRORMIMECONTENTINVALID';

    const ERRORMIMECONTENTINVALIDBASE64STRING = 'ERRORMIMECONTENTINVALIDBASE64STRING';

    const ERRORMISSINGARGUMENT = 'ERRORMISSINGARGUMENT';

    const ERRORMISSINGEMAILADDRESS = 'ERRORMISSINGEMAILADDRESS';

    const ERRORMISSINGEMAILADDRESSFORMANAGEDFOLDER = 'ERRORMISSINGEMAILADDRESSFORMANAGEDFOLDER';

    const ERRORMISSINGINFORMATIONEMAILADDRESS = 'ERRORMISSINGINFORMATIONEMAILADDRESS';

    const ERRORMISSINGINFORMATIONREFERENCEITEMID = 'ERRORMISSINGINFORMATIONREFERENCEITEMID';

    const ERRORMISSINGITEMFORCREATEITEMATTACHMENT = 'ERRORMISSINGITEMFORCREATEITEMATTACHMENT';

    const ERRORMISSINGMANAGEDFOLDERID = 'ERRORMISSINGMANAGEDFOLDERID';

    const ERRORMISSINGRECIPIENTS = 'ERRORMISSINGRECIPIENTS';

    const ERRORMISSINGUSERIDINFORMATION = 'ERRORMISSINGUSERIDINFORMATION';

    const ERRORMORETHANONEACCESSMODESPECIFIED = 'ERRORMORETHANONEACCESSMODESPECIFIED';

    const ERRORMOVECOPYFAILED = 'ERRORMOVECOPYFAILED';

    const ERRORMOVEDISTINGUISHEDFOLDER = 'ERRORMOVEDISTINGUISHEDFOLDER';

    const ERRORNAMERESOLUTIONMULTIPLERESULTS = 'ERRORNAMERESOLUTIONMULTIPLERESULTS';

    const ERRORNAMERESOLUTIONNOMAILBOX = 'ERRORNAMERESOLUTIONNOMAILBOX';

    const ERRORNAMERESOLUTIONNORESULTS = 'ERRORNAMERESOLUTIONNORESULTS';

    const ERRORNOAPPLICABLEPROXYCASSERVERSAVAILABLE = 'ERRORNOAPPLICABLEPROXYCASSERVERSAVAILABLE';

    const ERRORNOCALENDAR = 'ERRORNOCALENDAR';

    const ERRORNODESTINATIONCASDUETOKERBEROSREQUIREMENTS = 'ERRORNODESTINATIONCASDUETOKERBEROSREQUIREMENTS';

    const ERRORNODESTINATIONCASDUETOSSLREQUIREMENTS = 'ERRORNODESTINATIONCASDUETOSSLREQUIREMENTS';

    const ERRORNODESTINATIONCASDUETOVERSIONMISMATCH = 'ERRORNODESTINATIONCASDUETOVERSIONMISMATCH';

    const ERRORNOFOLDERCLASSOVERRIDE = 'ERRORNOFOLDERCLASSOVERRIDE';

    const ERRORNOFREEBUSYACCESS = 'ERRORNOFREEBUSYACCESS';

    const ERRORNONEXISTENTMAILBOX = 'ERRORNONEXISTENTMAILBOX';

    const ERRORNONPRIMARYSMTPADDRESS = 'ERRORNONPRIMARYSMTPADDRESS';

    const ERRORNOPROPERTYTAGFORCUSTOMPROPERTIES = 'ERRORNOPROPERTYTAGFORCUSTOMPROPERTIES';

    const ERRORNOPUBLICFOLDERREPLICAAVAILABLE = 'ERRORNOPUBLICFOLDERREPLICAAVAILABLE';

    const ERRORNOPUBLICFOLDERSERVERAVAILABLE = 'ERRORNOPUBLICFOLDERSERVERAVAILABLE';

    const ERRORNORESPONDINGCASINDESTINATIONSITE = 'ERRORNORESPONDINGCASINDESTINATIONSITE';

    const ERRORNOTDELEGATE = 'ERRORNOTDELEGATE';

    const ERRORNOTENOUGHMEMORY = 'ERRORNOTENOUGHMEMORY';

    const ERROROBJECTTYPECHANGED = 'ERROROBJECTTYPECHANGED';

    const ERROROCCURRENCECROSSINGBOUNDARY = 'ERROROCCURRENCECROSSINGBOUNDARY';

    const ERROROCCURRENCETIMESPANTOOBIG = 'ERROROCCURRENCETIMESPANTOOBIG';

    const ERROROPERATIONNOTALLOWEDWITHPUBLICFOLDERROOT = 'ERROROPERATIONNOTALLOWEDWITHPUBLICFOLDERROOT';

    const ERRORPARENTFOLDERIDREQUIRED = 'ERRORPARENTFOLDERIDREQUIRED';

    const ERRORPARENTFOLDERNOTFOUND = 'ERRORPARENTFOLDERNOTFOUND';

    const ERRORPASSWORDCHANGEREQUIRED = 'ERRORPASSWORDCHANGEREQUIRED';

    const ERRORPASSWORDEXPIRED = 'ERRORPASSWORDEXPIRED';

    const ERRORPHONENUMBERNOTDIALABLE = 'ERRORPHONENUMBERNOTDIALABLE';

    const ERRORPROPERTYUPDATE = 'ERRORPROPERTYUPDATE';

    const ERRORPROPERTYVALIDATIONFAILURE = 'ERRORPROPERTYVALIDATIONFAILURE';

    const ERRORPROXIEDSUBSCRIPTIONCALLFAILURE = 'ERRORPROXIEDSUBSCRIPTIONCALLFAILURE';

    const ERRORPROXYCALLFAILED = 'ERRORPROXYCALLFAILED';

    const ERRORPROXYGROUPSIDLIMITEXCEEDED = 'ERRORPROXYGROUPSIDLIMITEXCEEDED';

    const ERRORPROXYREQUESTNOTALLOWED = 'ERRORPROXYREQUESTNOTALLOWED';

    const ERRORPROXYREQUESTPROCESSINGFAILED = 'ERRORPROXYREQUESTPROCESSINGFAILED';

    const ERRORPROXYSERVICEDISCOVERYFAILED = 'ERRORPROXYSERVICEDISCOVERYFAILED';

    const ERRORPROXYTOKENEXPIRED = 'ERRORPROXYTOKENEXPIRED';

    const ERRORPUBLICFOLDERREQUESTPROCESSINGFAILED = 'ERRORPUBLICFOLDERREQUESTPROCESSINGFAILED';

    const ERRORPUBLICFOLDERSERVERNOTFOUND = 'ERRORPUBLICFOLDERSERVERNOTFOUND';

    const ERRORQUERYFILTERTOOLONG = 'ERRORQUERYFILTERTOOLONG';

    const ERRORQUOTAEXCEEDED = 'ERRORQUOTAEXCEEDED';

    const ERRORREADEVENTSFAILED = 'ERRORREADEVENTSFAILED';

    const ERRORREADRECEIPTNOTPENDING = 'ERRORREADRECEIPTNOTPENDING';

    const ERRORRECURRENCEENDDATETOOBIG = 'ERRORRECURRENCEENDDATETOOBIG';

    const ERRORRECURRENCEHASNOOCCURRENCE = 'ERRORRECURRENCEHASNOOCCURRENCE';

    const ERRORREMOVEDELEGATESFAILED = 'ERRORREMOVEDELEGATESFAILED';

    const ERRORREQUESTABORTED = 'ERRORREQUESTABORTED';

    const ERRORREQUESTSTREAMTOOBIG = 'ERRORREQUESTSTREAMTOOBIG';

    const ERRORREQUIREDPROPERTYMISSING = 'ERRORREQUIREDPROPERTYMISSING';

    const ERRORRESOLVENAMESINVALIDFOLDERTYPE = 'ERRORRESOLVENAMESINVALIDFOLDERTYPE';

    const ERRORRESOLVENAMESONLYONECONTACTSFOLDERALLOWED = 'ERRORRESOLVENAMESONLYONECONTACTSFOLDERALLOWED';

    const ERRORRESPONSESCHEMAVALIDATION = 'ERRORRESPONSESCHEMAVALIDATION';

    const ERRORRESTRICTIONTOOLONG = 'ERRORRESTRICTIONTOOLONG';

    const ERRORRESTRICTIONTOOCOMPLEX = 'ERRORRESTRICTIONTOOCOMPLEX';

    const ERRORRESULTSETTOOBIG = 'ERRORRESULTSETTOOBIG';

    const ERRORINVALIDEXCHANGEIMPERSONATIONHEADERDATA = 'ERRORINVALIDEXCHANGEIMPERSONATIONHEADERDATA';

    const ERRORSAVEDITEMFOLDERNOTFOUND = 'ERRORSAVEDITEMFOLDERNOTFOUND';

    const ERRORSCHEMAVALIDATION = 'ERRORSCHEMAVALIDATION';

    const ERRORSEARCHFOLDERNOTINITIALIZED = 'ERRORSEARCHFOLDERNOTINITIALIZED';

    const ERRORSENDASDENIED = 'ERRORSENDASDENIED';

    const ERRORSENDMEETINGCANCELLATIONSREQUIRED = 'ERRORSENDMEETINGCANCELLATIONSREQUIRED';

    const ERRORSENDMEETINGINVITATIONSORCANCELLATIONSREQUIRED = 'ERRORSENDMEETINGINVITATIONSORCANCELLATIONSREQUIRED';

    const ERRORSENDMEETINGINVITATIONSREQUIRED = 'ERRORSENDMEETINGINVITATIONSREQUIRED';

    const ERRORSENTMEETINGREQUESTUPDATE = 'ERRORSENTMEETINGREQUESTUPDATE';

    const ERRORSENTTASKREQUESTUPDATE = 'ERRORSENTTASKREQUESTUPDATE';

    const ERRORSERVERBUSY = 'ERRORSERVERBUSY';

    const ERRORSERVICEDISCOVERYFAILED = 'ERRORSERVICEDISCOVERYFAILED';

    const ERRORSTALEOBJECT = 'ERRORSTALEOBJECT';

    const ERRORSUBMISSIONQUOTAEXCEEDED = 'ERRORSUBMISSIONQUOTAEXCEEDED';

    const ERRORSUBSCRIPTIONACCESSDENIED = 'ERRORSUBSCRIPTIONACCESSDENIED';

    const ERRORSUBSCRIPTIONDELEGATEACCESSNOTSUPPORTED = 'ERRORSUBSCRIPTIONDELEGATEACCESSNOTSUPPORTED';

    const ERRORSUBSCRIPTIONNOTFOUND = 'ERRORSUBSCRIPTIONNOTFOUND';

    const ERRORSUBSCRIPTIONUNSUBSCRIBED = 'ERRORSUBSCRIPTIONUNSUBSCRIBED';

    const ERRORSYNCFOLDERNOTFOUND = 'ERRORSYNCFOLDERNOTFOUND';

    const ERRORTIMEINTERVALTOOBIG = 'ERRORTIMEINTERVALTOOBIG';

    const ERRORTIMEOUTEXPIRED = 'ERRORTIMEOUTEXPIRED';

    const ERRORTIMEZONE = 'ERRORTIMEZONE';

    const ERRORTOFOLDERNOTFOUND = 'ERRORTOFOLDERNOTFOUND';

    const ERRORTOKENSERIALIZATIONDENIED = 'ERRORTOKENSERIALIZATIONDENIED';

    const ERRORUPDATEPROPERTYMISMATCH = 'ERRORUPDATEPROPERTYMISMATCH';

    const ERRORUNIFIEDMESSAGINGDIALPLANNOTFOUND = 'ERRORUNIFIEDMESSAGINGDIALPLANNOTFOUND';

    const ERRORUNIFIEDMESSAGINGREQUESTFAILED = 'ERRORUNIFIEDMESSAGINGREQUESTFAILED';

    const ERRORUNIFIEDMESSAGINGSERVERNOTFOUND = 'ERRORUNIFIEDMESSAGINGSERVERNOTFOUND';

    const ERRORUNABLETOGETUSEROOFSETTINGS = 'ERRORUNABLETOGETUSEROOFSETTINGS';

    const ERRORUNSUPPORTEDSUBFILTER = 'ERRORUNSUPPORTEDSUBFILTER';

    const ERRORUNSUPPORTEDCULTURE = 'ERRORUNSUPPORTEDCULTURE';

    const ERRORUNSUPPORTEDMAPIPROPERTYTYPE = 'ERRORUNSUPPORTEDMAPIPROPERTYTYPE';

    const ERRORUNSUPPORTEDMIMECONVERSION = 'ERRORUNSUPPORTEDMIMECONVERSION';

    const ERRORUNSUPPORTEDPATHFORQUERY = 'ERRORUNSUPPORTEDPATHFORQUERY';

    const ERRORUNSUPPORTEDPATHFORSORTGROUP = 'ERRORUNSUPPORTEDPATHFORSORTGROUP';

    const ERRORUNSUPPORTEDPROPERTYDEFINITION = 'ERRORUNSUPPORTEDPROPERTYDEFINITION';

    const ERRORUNSUPPORTEDQUERYFILTER = 'ERRORUNSUPPORTEDQUERYFILTER';

    const ERRORUNSUPPORTEDRECURRENCE = 'ERRORUNSUPPORTEDRECURRENCE';

    const ERRORUNSUPPORTEDTYPEFORCONVERSION = 'ERRORUNSUPPORTEDTYPEFORCONVERSION';

    const ERRORUPDATEDELEGATESFAILED = 'ERRORUPDATEDELEGATESFAILED';

    const ERRORUSERNOTUNIFIEDMESSAGINGENABLED = 'ERRORUSERNOTUNIFIEDMESSAGINGENABLED';

    const ERRORVOICEMAILNOTIMPLEMENTED = 'ERRORVOICEMAILNOTIMPLEMENTED';

    const ERRORVALUEOUTOFRANGE = 'ERRORVALUEOUTOFRANGE';

    const ERRORVIRUSDETECTED = 'ERRORVIRUSDETECTED';

    const ERRORVIRUSMESSAGEDELETED = 'ERRORVIRUSMESSAGEDELETED';

    const ERRORWEBREQUESTININVALIDSTATE = 'ERRORWEBREQUESTININVALIDSTATE';

    const ERRORWIN32INTEROPERROR = 'ERRORWIN32INTEROPERROR';

    const ERRORWORKINGHOURSSAVEFAILED = 'ERRORWORKINGHOURSSAVEFAILED';

    const ERRORWORKINGHOURSXMLMALFORMED = 'ERRORWORKINGHOURSXMLMALFORMED';

    const ERRORWRONGSERVERVERSION = 'ERRORWRONGSERVERVERSION';

    const ERRORWRONGSERVERVERSIONDELEGATE = 'ERRORWRONGSERVERVERSIONDELEGATE';

    const ERRORMISSINGINFORMATIONSHARINGFOLDERID = 'ERRORMISSINGINFORMATIONSHARINGFOLDERID';

    const ERRORDUPLICATESOAPHEADER = 'ERRORDUPLICATESOAPHEADER';

    const ERRORSHARINGSYNCHRONIZATIONFAILED = 'ERRORSHARINGSYNCHRONIZATIONFAILED';

    const ERRORSHARINGNOEXTERNALEWSAVAILABLE = 'ERRORSHARINGNOEXTERNALEWSAVAILABLE';

    const ERRORFREEBUSYDLLIMITREACHED = 'ERRORFREEBUSYDLLIMITREACHED';

    const ERRORINVALIDGETSHARINGFOLDERREQUEST = 'ERRORINVALIDGETSHARINGFOLDERREQUEST';

    const ERRORNOTALLOWEDEXTERNALSHARINGBYPOLICY = 'ERRORNOTALLOWEDEXTERNALSHARINGBYPOLICY';

    const ERRORUSERNOTALLOWEDBYPOLICY = 'ERRORUSERNOTALLOWEDBYPOLICY';

    const ERRORPERMISSIONNOTALLOWEDBYPOLICY = 'ERRORPERMISSIONNOTALLOWEDBYPOLICY';

    const ERRORORGANIZATIONNOTFEDERATED = 'ERRORORGANIZATIONNOTFEDERATED';

    const ERRORMAILBOXFAILOVER = 'ERRORMAILBOXFAILOVER';

    const ERRORINVALIDEXTERNALSHARINGINITIATOR = 'ERRORINVALIDEXTERNALSHARINGINITIATOR';

    const ERRORMESSAGETRACKINGPERMANENTERROR = 'ERRORMESSAGETRACKINGPERMANENTERROR';

    const ERRORMESSAGETRACKINGTRANSIENTERROR = 'ERRORMESSAGETRACKINGTRANSIENTERROR';

    const ERRORMESSAGETRACKINGNOSUCHDOMAIN = 'ERRORMESSAGETRACKINGNOSUCHDOMAIN';

    const ERRORUSERWITHOUTFEDERATEDPROXYADDRESS = 'ERRORUSERWITHOUTFEDERATEDPROXYADDRESS';

    const ERRORINVALIDORGANIZATIONRELATIONSHIPFORFREEBUSY = 'ERRORINVALIDORGANIZATIONRELATIONSHIPFORFREEBUSY';

    const ERRORINVALIDFEDERATEDORGANIZATIONID = 'ERRORINVALIDFEDERATEDORGANIZATIONID';

    const ERRORINVALIDEXTERNALSHARINGSUBSCRIBER = 'ERRORINVALIDEXTERNALSHARINGSUBSCRIBER';

    const ERRORINVALIDSHARINGDATA = 'ERRORINVALIDSHARINGDATA';

    const ERRORINVALIDSHARINGMESSAGE = 'ERRORINVALIDSHARINGMESSAGE';

    const ERRORNOTSUPPORTEDSHARINGMESSAGE = 'ERRORNOTSUPPORTEDSHARINGMESSAGE';

    const ERRORAPPLYCONVERSATIONACTIONFAILED = 'ERRORAPPLYCONVERSATIONACTIONFAILED';

    const ERRORINBOXRULESVALIDATIONERROR = 'ERRORINBOXRULESVALIDATIONERROR';

    const ERROROUTLOOKRULEBLOBEXISTS = 'ERROROUTLOOKRULEBLOBEXISTS';

    const ERRORRULESOVERQUOTA = 'ERRORRULESOVERQUOTA';

    const ERRORNEWEVENTSTREAMCONNECTIONOPENED = 'ERRORNEWEVENTSTREAMCONNECTIONOPENED';

    const ERRORMISSEDNOTIFICATIONEVENTS = 'ERRORMISSEDNOTIFICATIONEVENTS';
}
