language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --no-ansi
  - wget https://scrutinizer-ci.com/ocular.phar
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
  - composer cs

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false
